// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rguckkvwvgwrpdpavpga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndWNra3Z3dmd3cnBkcGF2cGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MTIzNjAsImV4cCI6MjA1MDM4ODM2MH0.AY45vdoPuqMYMt2j1iJpNwKscZFYSVbt-jCsamQHNd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);